security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/efc/login$
            security: false

        secured_area:
            pattern: ^/efc/
            form_login:
                check_path: efc_security_check
                login_path: efc_login
            logout:
                path:   efc_logout
                target: efc_welcome
                invalidate_session: false # due to bug in PHP (https://groups.google.com/forum/#!topic/symfony-devs/Q-f0lKT7OZ8)
            anonymous: ~
            #http_basic:
            #    realm: "Secured EFC Mailproxy Area"

    access_control:
        #- { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        - { path: ^/efc/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
