#efc_mailproxy_homepage:
#    pattern:  /account/{username}
#    defaults: { _controller: EFCMailproxyBundle:Default:index }

efc_welcome:
    pattern:  /
    defaults: { _controller: EFCMailproxyBundle:Default:welcome }

efc_secured:
    resource: "@EFCMailproxyBundle/Controller/SecuredController.php"
    type:     annotation