efc_mailproxy_homepage:
    pattern:  /account/{username}
    defaults: { _controller: EFCMailproxyBundle:Default:index }

_account_secured:
    resource: "@EFCMailproxyBundle/Controller/SecuredController.php"
    type:     annotation