parameters:
#    efc_mailproxy.example.class: EFC\MailproxyBundle\Example

services:
#    efc_mailproxy.example:
#        class: %efc_mailproxy.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
